-----DISABLE INDEXES--------------------
spool disable_bnft_fact_ndx.out

ALTER SESSION SET DDL_LOCK_TIMEOUT=600;

REM ** alter table ecisdrdm.bnft_curr_fact disable CONSTRAINT BNFT_CURR_FACN_PK CASCADE;

Alter index ECISDRDM.BNFT_CURR_FACT_BNFTPMMID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_BNFHISACTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_BNFTPMSTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_CSECMPXID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_BENENDDTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_ATTYID_BMX unusable;
REM ** Alter index ECISDRDM.BNFT_CURR_FACT_ATTENDDTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_ASGNDTMID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_ASGNDDTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_APPLICATIID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_ADJTNRYID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_ADJTNRDTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_ACTNTMINID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_ACTNDTINID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_DATE_INIT_BJIX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_USCISEMPID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_UPDTUSRID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_SVCCTRID_BMX unusable;
REM ** Alter index ECISDRDM.BNFT_CURR_FACT_SRC_SYS_ID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_REQFRMRSID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_REQCLPREID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_PRRTYDTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_MLSTNSTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_INITRDTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_INITRCTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_GRTCLAPRID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_GRFRMRSNID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_FRMTYPID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_FRMID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_DECDTID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_CSEPRRTYID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_CSEID_BMX unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_FILECDID_BTI unusable;
Alter index ECISDRDM.BNFT_CURR_FACT_BENEID_BTI unusable;
REM ** Alter index ECISDRDM.BNFT_CURR_FACT_PK unusable;
Alter index ECISDRDM.BNFTN_FACT_BENTRCZPID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_LOADDTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_PMNTDTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_RSDCSTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_COPOSIT2_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_JRSDCTNID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_BNFHISACTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_COPOSIT1_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_FRMTYPID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_MLSTNSTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_BENCTRYSDCID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_POEID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_GRTCLAPRID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_CSECMPXID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_FRMID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_REQFRMRSID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_LOADID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_BENCTRYBRTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_DECDTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_GRFRMRSNID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_PRPRID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_PRRTYDTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_SVCCTRID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_COPOSIT3_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_CSEPRRTYID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_OFFCID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_DATE_CAL_BJIX unusable;
Alter index ECISDRDM.BNFTN_FACT_BNFTPMSTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_ASGNDDTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_ATTYID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_REQCLPREID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_ADJTNRDTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_BENENDDTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_USCISEMPID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_RMTRID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_ATTENDDTID_BMX unusable;
REM ** Alter index ECISDRDM.BNFTN_FACT_ACTNDTINID_BMX unusable;
REM ** Alter index ECISDRDM.BNFTN_FACT_SRC_SYS_ID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_PREVLSTNSTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_INITRDTID_BMX unusable;
Alter index ECISDRDM.BNFTN_FACT_PETNRAPPID_BTI unusable;
Alter index ECISDRDM.BNFTN_FACT_CSEID_BTI unusable;
REM ** Alter index ECISDRDM.BNFTN_FACT_BNFTFACTID_BTI unusable;
Alter index ECISDRDM.BNFTN_FACT_APPLICATIID_BTI unusable;
Alter index ECISDRDM.BNFTN_FACT_FILECDID_BTI unusable;
Alter index ECISDRDM.BNFTN_FACT_BENEID_BMX unusable;

spool off;



